name: CI

on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - release/*
  pull_request:
    branches:
      - master
      - develop

env:
  CONFIGURATION: 'Release'

jobs:

  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [ 'win-x86', 'win-x64']
        dotnet: [ '3.1.100' ]
    steps:

    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Build for ${{ matrix.runtime }}
      run: dotnet build `
        --configuration ${{ CONFIGURATION }} `
        --runtime ${{ matrix.runtime }} `
        .\NraDatabaseExport.sln

    - name: Publish for ${{ matrix.runtime }}
      run: |
        dotnet publish `
          --configuration ${{ CONFIGURATION }} `
          --runtime ${{ matrix.runtime }} `
          --output .\.publish\${{ matrix.runtime }}\ `
          .\src\NraDatabaseExport.App\
